### ISSUE TITLE
Function return type have different color type

### ISSUE THREAD

**Issue by lijiarui** [qhduan/wechaty-doc#11]
![image](https://user-images.githubusercontent.com/6419514/42521014-58d1f022-849a-11e8-85e3-208deb0c6577.png)

**Comment by lijiarui** [comment]
same with gender:

![image](https://user-images.githubusercontent.com/6419514/42521316-1707ed12-849b-11e8-99f7-4316450a4aab.png)

**Comment by lijiarui** [comment]
I thinks this is relate to #7

**Comment by qhduan** [comment]
done with 5670fe93b5b2d48ccafc1b2d5430e3a8353e7f0d
