### ISSUE TITLE
Typedefs cannot jump in a right way

### ISSUE THREAD

**Issue by lijiarui** [qhduan/wechaty-doc#18]
### Issue Description
https://qhduan.github.io/wechaty-doc/#/api/?id=wechatyoptions cannot jump to the right way

### Actual 
When I click `WechatyOptions ` It should jump to the right postion
![image](https://user-images.githubusercontent.com/6419514/42562656-e2a92f38-852e-11e8-91d2-9f5966ecc10a.png)

While when I click this, it jump to:
![image](https://user-images.githubusercontent.com/6419514/42562710-0611414a-852f-11e8-8033-cf0deff9a57c.png)

### Expect
While when I click this, it jump to: WechatyOptions detail page:
![image](https://user-images.githubusercontent.com/6419514/42562733-1a719fa4-852f-11e8-8549-7a2ed02ba218.png)

All Typedefs have the same problem
- [x] PuppetName
- [x] WechatyOptions
- [x] WechatyEventName
- [x] RoomQueryFilter
- [x] RoomEventName
- [x] RoomEventFunction
- [x] RoomMemberQueryFilter
- [x] ContactQueryFilter

**Comment by qhduan** [comment]
fixed with ecd26a134b2f0fafd90d0849ce78122b2521e2d8

**Comment by lijiarui** [comment]
good
