### ISSUE TITLE
Chinese version wechaty tab will go to English version

### ISSUE THREAD

**Issue by lijiarui** [qhduan/wechaty-doc#2]
https://qhduan.github.io/wechaty-doc/#/zh In this page, when I click here:
![image](https://user-images.githubusercontent.com/6419514/42410133-6eb292aa-8217-11e8-8f85-e700206a071e.png)

It will jump to https://qhduan.github.io/wechaty-doc/

**Comment by qhduan** [comment]
all these button should goto top of page now
