### ISSUE TITLE
wechaty类

### ISSUE THREAD

**Issue by windmemory** [qhduan/wechaty-doc#20]
- [x] If you want to know how to send message, see Message If you want to knwo how to get contact, see Contact
should be two lines

- [x] `wechaty.on(event, listener)` section, Returns: Wechaty -- this is for chain.
better to have an example to show how to chain.

- [ ] Example code section's title should explains a little what this example does, or at least tell the user that is the example for. 

- [x] `wechaty.init()` is deprecated, we should tell user which one to replace this. Maybe add `use start instead`.

- [x] `wechaty.start()` Maybe we could reminds the user that most of the bot operation needs to be triggered after `start()` is done

- [x] instance example is still using `init()`, should be replaced by `start()`

**Comment by lijiarui** [comment]
fix

**Comment by lijiarui** [comment]
> Example code section's title should explains a little what this example does, or at least tell the user that is the example for.

Which Example code and add what content

**Comment by windmemory** [comment]
```
Return the type of: Wechaty - this is for chaining, see advanced [chaining usage](link-to-chaining-page)
```

### Page in somewhere, maybe FAQ or Other
```
Method chaining, also known as named parameter idiom, is a common syntax for invoking multiple method calls in object-oriented programming languages. Each method returns an object, allowing the calls to be chained together in a single statement without requiring variables to store the intermediate results. [More info](https://en.wikipedia.org/wiki/Method_chaining)

`Wechaty` class support method chaining, you could write code like this:
``
const { Wechaty } = require('wechaty')
const bot = new Wechaty()
.on('scan', (qrcode, status) =>  {})
.on('login', user => {})
.on('message', message => {})
.start()
``
```

**Comment by lijiarui** [comment]
@windmemory done
