### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by windmemory** [qhduan/wechaty-doc#22]
- [ ] Tips under `contact.type()` and `contact.gender()` is duplicate with the content in return type, might consider to remove it.

**Comment by lijiarui** [comment]
What do you mean by duplicate
![image](https://user-images.githubusercontent.com/6419514/42616456-f05a0bcc-85e0-11e8-8830-69dbacc12b19.png)

**Comment by qhduan** [comment]
@windmemory .gender() return ContactGender, male/female/unknown, .type() return ContactType, Official/Personal/Unknown
